### ISSUE TITLE
Can't autopublish to Chrome webstore : "invalid user"

### ISSUE THREAD

**Issue by Narno** [prose/browser-extensions#13]
@tristen, I think my user is not allowed to publish in the name of the "prose" group:
> cd build && webstore upload --auto-publish
> Response code 400 (Bad Request)
> {
>     "error": "invalid_user"
> }

https://www.travis-ci.org/prose/browser-extensions/builds/294925578

Maybe I must be "co-owner" of the group or something like that :-/

(see #12 for reference)

**Comment by Narno** [comment]
(see #12 for reference)

**Comment by tristen** [comment]
uh oh! Want to give it another try? I've adjusted your role in the group to owner 👍

**Comment by Narno** [comment]
> Response code 400 (Bad Request)
> {
>     "error": "invalid_grant"
> }
Haha, I don't understand how it works! XD

**Comment by Narno** [comment]
I had redo all steps and... it works! :champagne: 
```bash
> Edit-in-Prose@1.1.0 release:cws /home/travis/build/prose/browser-extensions
> cd build && webstore upload --auto-publish
Publish Status: OK
> Edit-in-Prose@1.1.0 release:amo /home/travis/build/prose/browser-extensions
> cd build && webext submit
Building web extension from /home/travis/build/prose/browser-extensions/build
Validating add-on [............................................................]
Validation results: https://addons.mozilla.org/en-US/developers/upload/4bc7a1a8256544d2850ea2f1cd346063
Your add-on has been submitted for review. It passed validation but could not be automatically signed because this is a listed add-on.
```
https://www.travis-ci.org/prose/browser-extensions/builds/294925578

**Comment by ajsb85** [comment]
Mozilla Add-ons: Edit in Prose 1.1.1 Approved

The add-on, Edit in Prose 1.1.1, has been approved and is now available for download in our gallery at https://addons.mozilla.org/addon/prose/
