### ISSUE TITLE
Button not showing

### ISSUE THREAD

**Issue by orschiro** [prose/browser-extensions#5]
Dear all, 

I installed the [Chrome extension](https://chrome.google.com/webstore/detail/prose/onippmookoohgjgccejcjmlpoohbjgjn) on Chromium 45 but the button is not showing up. 

Can someone confirm this?

Thankfully,

Robert

**Comment by Narno** [comment]
It seems the DOM has changed again and the query selector is broken...

**Comment by orschiro** [comment]
Dear @Narno,

Thank you for quick fix! 

This is a good reference for me to fix it myself next time. ツ

Thankfully,

Robert

**Comment by Narno** [comment]
You're welcome @orschiro ;-)

@tristen could you reviews my PR please?

**Comment by tristen** [comment]
Thanks for the fix @Narno! Publishing shortly.

**Comment by orschiro** [comment]
It's showing up. Thanks for the quick fix, guys!

![image](https://cloud.githubusercontent.com/assets/170947/10220347/0ff63132-6847-11e5-9169-656e77313aee.png)

Warmly,

Robert

**Comment by Narno** [comment]
Yeah! o/
